# Alibaba Cloud Function Compute Build CI
name: build

# 监听
on:
  push:
    branches:
      - master
      - develop
      - release/*

# 任务
jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [10.x]
        os: [macOS-latest]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Download Node.js
      run: |
        wget https://nodejs.org/dist/latest-v13.x/node-v13.5.0-linux-x64.tar.gz
        tar xzvf node-v13.5.0-linux-x64.tar.gz node-v13.5.0-linux-x64/bin/node
        cp node-v13.5.0-linux-x64/bin/node bin/node
        rm -rf node-v13.5.0-linux-x64*

    - name: Install Dependencie
      run: |
        yarn install
        yarn global add @alicloud/fun rimraf
  
    - name: Deploy
      run: |
        fun deploy -t template.yml
      env:
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        REGION: ${{ secrets.REGION }}
        ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
        ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
        TIMEOUT: ${{ secrets.TIMEOUT }}
        RETRIES: ${{ secrets.RETRIES }}
